<?php
/** @var $block \Study\ProductLikes\Block\Product\LikeButton
 *
 */
if($block->isLogged()){
    $customerId = $block->getCustomerId();
    $productId = $block->getProductId();
    $isLiked = $block->isThisProductLiked($productId, $customerId);
}
?>

<?php if($block->isLogged()): ?>
    <script type="text/javascript">
        require(["jquery",'mage/url'], function($, url){
            "use strict";
            $(document).on('click','.like',function(){
                jQuery.ajax({
                    url: '/likes/index/likeproduct',
                    type: "POST",
                    data: {
                        productId:<?=$productId?>,
                        customerId:<?=$customerId?>
                    }
                });
            });
        });
    </script>
<?php if(!$isLiked): ?>
        <div class="actions">
            <button type="button" title="<?php echo $block::TITLE_ENABLED ?>" class="action primary like" id="like"
                    onClick="window.location.reload();">
                <span><span><i class="like-span"></i><?php echo $block::TITLE_ENABLED ?></span></span></button>
        </div>
<?php endif; ?>
<?php if($isLiked): ?>
        <div class="actions">
            <button type="button" title="<?php echo $block::TITLE_DISABLED ?>"
                    class="action primary like" id="like" disabled="disabled">
                <span><span><i class="like-span"></i><?php echo $block::TITLE_DISABLED ?></span></span></button>
        </div>
<?php endif; ?>

<?php endif; ?>
