<?php
/** @var $block \Study\ProductLikes\Block\Product\LikeButton
 *
 */
$isLikedByCustomer = $block->isThisProductLikedByCustomer();
$isLikedByGuest = $block->isThisProductLikedByThisGuest();
?>
<script type="text/x-magento-init">
    {
        "#like": {
            "transferDataToController": {}
        }
    }
</script>
<?php if(!$isLikedByGuest && !$isLikedByCustomer): ?>
        <div class="actions">
            <button type="button" title="<?php echo "I like this product" ?>" class="action primary like" id="like">
                <span><span><i class="like-span"></i><?php echo "I like this product" ?></span></span></button>
        </div>
<?php endif; ?>
<?php if(($block->isLogged() && $isLikedByCustomer ) || $isLikedByGuest): ?>
        <div class="actions">
            <button type="button" title="<?php echo "Already liked" ?>"
                    class="action primary like" id="like" disabled="disabled">
                <span><span><i class="like-span"></i><?php echo "Already liked" ?></span></span></button>
        </div>
<?php endif; ?>
