<?php
/* @var \Study\InversedRelatedProducts\Block\Product\View\Extra $block */
$inversedRelatedProductsArray = $block->getInveresedRealtedProductsColection();
?>

<?php if ($block->canShowInversedProducts() && !empty($inversedRelatedProductsArray->getItems())): ?>
    <strong class="product name product-item-name">Please also check related products:
        <?php foreach ($inversedRelatedProductsArray as $inversedRelatedProduct): ?>
            <a class="product-item-link"
               title="<?= $inversedRelatedProduct->getName() ?>"
               href="<?= $inversedRelatedProduct->getProductUrl() ?>">
                <?= $inversedRelatedProduct->getName() ?></a>
        <?php endforeach; ?>
    </strong>
<?php endif; ?>
