<?php
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?= $block->getGridHtml() ?>
<input type="hidden" name="rh_products" data-form-part="promotions_edit_form" id="rh_products" value=""/>
<script type="text/x-magento-init">
    {
        "*": {
            "Study_Promotions/js/assign-products": {
                "selectedProducts":  <?= '{}' ?>,
                "gridJsObjectName": <?= /* @escapeNotVerified */'"' . $gridJsObjectName . '"' ?: '{}' ?>
            }
        }
    }
</script>
<script>
    require('mage/apply/main').apply();
</script>
